/**
 * \file
 *
 * \brief Driver initialization.
 *
 (c) 2020 Microchip Technology Inc. and its subsidiaries.

    Subject to your compliance with these terms,you may use this software and
    any derivatives exclusively with Microchip products.It is your responsibility
    to comply with third party license terms applicable to your use of third party
    software (including open source software) that may accompany Microchip software.

    THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER
    EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED
    WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A
    PARTICULAR PURPOSE.

    IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE,
    INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND
    WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS
    BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO THE
    FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN
    ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY,
    THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 *
 */

/*
 * Code generated by START.
 *
 * This file will be overwritten when reconfiguring your START project.
 * Please copy examples or other code you want to keep to a separate file
 * to avoid losing it when reconfiguring.
 */

#include "driver_init.h"
#include <system.h>

/* configure the pins and initialize the registers */
void USART_0_initialization(void)
{

	// Set pin direction to input
	Bluetooth_RX_set_dir(PORT_DIR_IN);

	Bluetooth_RX_set_pull_mode(
	    // <y> Pull configuration
	    // <id> pad_pull_config
	    // <PORT_PULL_OFF"> Off
	    // <PORT_PULL_UP"> Pull-up
	    PORT_PULL_OFF);

	// Set pin direction to output

	Bluetooth_TX_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	Bluetooth_TX_set_dir(PORT_DIR_OUT);

	USART_0_init();
}

/* configure the pins and initialize the registers */
void USART_1_initialization(void)
{

	// Set pin direction to input
	SYBT_RX_set_dir(PORT_DIR_IN);

	SYBT_RX_set_pull_mode(
	    // <y> Pull configuration
	    // <id> pad_pull_config
	    // <PORT_PULL_OFF"> Off
	    // <PORT_PULL_UP"> Pull-up
	    PORT_PULL_OFF);

	// Set pin direction to output

	SYBT_TX_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	SYBT_TX_set_dir(PORT_DIR_OUT);

	USART_1_init();
}

/* configure the pins and initialize the registers */
void USART_3_initialization(void)
{

	// Set pin direction to input
	AVR_RX_TINY_TX_set_dir(PORT_DIR_IN);

	AVR_RX_TINY_TX_set_pull_mode(
	    // <y> Pull configuration
	    // <id> pad_pull_config
	    // <PORT_PULL_OFF"> Off
	    // <PORT_PULL_UP"> Pull-up
	    PORT_PULL_OFF);

	// Set pin direction to output

	AVR_TX_TINY_RX_set_level(
	    // <y> Initial level
	    // <id> pad_initial_level
	    // <false"> Low
	    // <true"> High
	    false);

	AVR_TX_TINY_RX_set_dir(PORT_DIR_OUT);

	USART_3_init();
}

void EVENT_SYSTEM_0_initialization(void)
{

	EVENT_SYSTEM_0_init();
}

/* Configure pins and initialize registers */
void ADC_0_initialization(void)
{


	LXvolts_set_isc(PORT_ISC_INPUT_DISABLE_gc);

	LXvolts_set_pull_mode(PORT_PULL_OFF);

	Int_Temp_set_isc(PORT_ISC_INPUT_DISABLE_gc);

	Int_Temp_set_pull_mode(PORT_PULL_OFF);

	SYBT5_Connected_set_isc(PORT_ISC_INPUT_DISABLE_gc);				//Temporary setup as digital input----------------------------------------------------------

	SYBT5_Connected_set_pull_mode(PORT_PULL_OFF);						//Temporary setup as digital input----------------------------------------------------------

	TwentyFourVolt_set_isc(PORT_ISC_INPUT_DISABLE_gc);

	TwentyFourVolt_set_pull_mode(PORT_PULL_OFF);

	SYBT_Resistor_set_isc(PORT_ISC_INPUT_DISABLE_gc);
	// Disable pull-up resistor
	SYBT_Resistor_set_pull_mode(PORT_PULL_OFF);

	// Disable digital input buffer
	SYBT_Temp_set_isc(PORT_ISC_INPUT_DISABLE_gc);
	// Disable pull-up resistor
	SYBT_Temp_set_pull_mode(PORT_PULL_OFF);

	// Disable digital input buffer
	E3S_Sense_set_isc(PORT_ISC_INPUT_DISABLE_gc);
	// Disable pull-up resistor
	E3S_Sense_set_pull_mode(PORT_PULL_OFF);

	// Disable digital input buffer
	SYBT_Volts_set_isc(PORT_ISC_INPUT_DISABLE_gc);
	// Disable pull-up resistor
	SYBT_Volts_set_pull_mode(PORT_PULL_OFF);

	// Disable digital input buffer
	Load_Test_set_isc(PORT_ISC_INPUT_DISABLE_gc);
	// Disable pull-up resistor
	Load_Test_set_pull_mode(PORT_PULL_OFF);

	// Disable digital input buffer
	Six_Volts_set_isc(PORT_ISC_INPUT_DISABLE_gc);
	// Disable pull-up resistor
	Six_Volts_set_pull_mode(PORT_PULL_OFF);

	// Disable digital input buffer													//Using as a digital input for the moment. 
	//SYBT5_Sense_set_isc(PORT_ISC_INPUT_DISABLE_gc);
	// Disable pull-up resistor
	//SYBT5_Sense_set_pull_mode(PORT_PULL_OFF);

	// Disable digital input buffer
	HS_set_isc(PORT_ISC_INPUT_DISABLE_gc);
	// Disable pull-up resistor
	HS_set_pull_mode(PORT_PULL_OFF);

	ADC_0_init();
}

/* Initialize registers */
void FLASH_0_initialization(void)
{
	FLASH_0_init();
}

/**
 * \brief System initialization
 */
void system_init()
{
	mcu_init();

	ATTINY_PB0_set_dir(PORT_DIR_IN);				// Not yet used	
	
	ATTINY_PB0_set_pull_mode(PORT_PULL_UP);

	MarchingAnts_set_level(false);

	MarchingAnts_set_dir(PORT_DIR_OUT);

	ReverseMarchingAnts_set_level(false);
	
	ReverseMarchingAnts_set_dir(PORT_DIR_OUT);				//
	
	ATTINY_PA6_set_level(false);

	ATTINY_PA6_set_dir(PORT_DIR_OUT);

	PWR_ON_set_level(true);

	PWR_ON_set_dir(PORT_DIR_OUT);

	FT2_set_level( false);

	FT2_set_dir(PORT_DIR_OUT);
	
	EPO_set_level(true);
	
	EPO_set_dir(PORT_DIR_OUT);

	Beeper_set_level(false);

	Beeper_set_dir(PORT_DIR_OUT);

	LargeChip_Display_set_level(true);

	LargeChip_Display_set_dir(PORT_DIR_OUT);

	LED1_set_level(false);

	LED1_set_dir(PORT_DIR_OUT);

	SYBT5_RLY_set_level(false);

	SYBT5_RLY_set_dir(PORT_DIR_OUT);

	LED4_set_level(true);

	LED4_set_dir(PORT_DIR_OUT);

	BlueLED_set_level(false);

	BlueLED_set_dir(PORT_DIR_OUT);
	
	//SYBT5_Connected_set_dir(PORT_DIR_IN);				//-------------------------------------Temporary set as digital input-------------------------------
	
	//SYBT5_Connected_set_pull_mode(PORT_PULL_OFF);		//-------------------------------------Temporary set as digital input--------------------------------

	YellowLED_set_level(true);

	YellowLED_set_dir(PORT_DIR_OUT);

	Main_Button_set_dir(PORT_DIR_IN);

	Main_Button_set_pull_mode(PORT_PULL_OFF);

	Load_Relay_set_level(false);

	Load_Relay_set_dir(PORT_DIR_OUT);

	Load_IGBT_set_level(false);

	Load_IGBT_set_dir(PORT_DIR_OUT);

	CLKCTRL_init();

	USART_0_initialization();

	USART_1_initialization();

	USART_3_initialization();

	EVENT_SYSTEM_0_initialization();

	SLPCTRL_init();

	CPUINT_init();

	ADC_0_initialization();

	FLASH_0_initialization();

	VREF_0_init();

	BOD_init();

	WDT_0_init();
}
